### ISSUE TITLE
关于phash

### ISSUE THREAD

**Issue by Usernamezhx** [xuehuachunsheng/DupImageDetection#1]
你好，非常感谢你的工作，不知道你在实际测试中有没有发现phash的缺点，对于外轮廓相似的非纯色背景的样本是很难处理的，我尝试过颜色直方图的方案缓解但是收效甚微

**Comment by xuehuachunsheng** [comment]
外轮廓相似的非纯色背景样本之间，你认为它们是相同的还是不同的呢？
